version: 2.1
orbs: 
  slack: circleci/slack@4.10.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      #- restore_cache:
      #    keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            
            npm install
            npm run build
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Unfortunately FrontEnd Build has failed, review YOUR CODE",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
            
      #- save_cache:
      #    paths: [frontend/node_modules]
      #    key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      #- restore_cache:
      #    keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend 
            npm install 
            npm run build
      - slack/notify:
          event: fail
          template: basic_fail_1
  test-frontend : 
    docker : 
      - image: circleci/node:13.8.0
    steps : 
      - checkout
      - run: 
          name: FrontEnd Test 
          command : |
            cd frontend
            npm install 
            npm run test
      - slack/notify:
          event: fail
          template: basic_fail_1
  
  test-backend : 
    docker : 
      - image: circleci/node:13.8.0
    steps : 
      - checkout
      - run: 
          name: BackEnd Test 
          command : |
            cd backend
            npm install 
            npm run test
      - slack/notify:
          event: fail
          template: basic_fail_1
  scan-frontend : 
    docker : 
      - image: circleci/node:13.8.0
    steps : 
      - checkout
      - run :
          name : FrontEnd Secuirty Check
          command : |
            cd frontend 
            npm install 
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical  
      - slack/notify:
          event: fail
          template: basic_fail_1

  scan-backend :  
    docker : 
      - image: circleci/node:13.8.0
    steps : 
      - checkout
      - run : 
          name :  BackEnd Secuirty Check
          command : |
            cd backend
            npm install 
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Congratulations, the CI pipline ran Succefully !! *",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
        #- save_cache:
        #    paths: [backend/node_modules]
        #    key: backend-build

workflows:
  default:
    jobs:
      - build-frontend :
          context:
              - Udapeople 

      - build-backend :
          context:
              - Udapeople
      - test-frontend : 
            requires : 
            - build-frontend 
            context:
              - Udapeople
      - test-backend : 
            requires : 
            - build-backend
            context:
              - Udapeople
      - scan-frontend : 
          requires : 
            - test-frontend 
          context:
              - Udapeople
      - scan-backend : 
          requires : 
            - test-backend
          context:
              - Udapeople

