- name : 'create User for Node Exporter'
  shell: |
    sudo useradd --no-create-home node_exporter

- name : 'install Node Exporter binaries'
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name : 'Configure the node service'
  become: true
  become_method: sudo
  become_user: root
  copy :
    src : node-exporter
    dest : /etc/systemd/system/node-exporter.service

- name : 'Configure systemd'
  become: true
  become_method: sudo
  become_user: root
  shell : |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter
